### ISSUE TITLE
Todo: title slide

### ISSUE THREAD

**Issue by matt-dray** [matt-dray/gds-xaringan#1]
Can set a bunch of title slide parameters, or make sure the Rmd includes the right code.

- [x] Background grey – change title slide bg colour
- [x] First line bold ('Firstname Surname') – ~~change H1 or~~ create tag
- [x] Text in lower left – padding applied in Rmd
- [ ] Ability to add logo to upper left – padding applied in Rmd
