### ISSUE TITLE
Todo: heading slides

### ISSUE THREAD

**Issue by matt-dray** [matt-dray/gds-xaringan#2]
There's a text heading slide (blue background) and image heading slide (full-slide image).

- [x] Vertical centering of text – probably hacky padding
- [x] Ability to make text black if it overlays a light image – .black[] tag
- [x] Make sure footer doesn't appear over background image
